version: 2
jobs:
  build:
    docker:
      - image: ubuntu:xenial

    steps:
      - checkout
      - run:
          name: "Install Deps"
          command: |
            dpkg --add-architecture i386
            apt-get update && apt-get install -y build-essential g++-multilib gcc-multilib libc6-dev-i386 zlib1g-dev zlib1g-dev:i386 wget
            wget -O premake.tar.gz "https://github.com/premake/premake-core/releases/download/v5.0.0-alpha14/premake-5.0.0-alpha14-linux.tar.gz"
            tar xvzf premake.tar.gz
            ./premake5 --os=linux --file=BuildProjects.lua gmake

      - run:
          name: "Build x86"
          command: |
            cd solutions/linux-gmake
            make

      - run:
          name: "Build x86_64"
          command: |
            cd solutions/linux-gmake
            make config=release_x86_64

      - store_artifacts:
          path: ./out/linux
